# Generated by Django 4.2.30 on 2026-05-24 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap_fuel', 'SAP Fuel & Procurement'), ('utility_electricity', 'Utility Electricity'), ('travel', 'Corporate Travel')], max_length=30)),
                ('file_name', models.CharField(help_text='Original uploaded filename', max_length=500)),
                ('file_hash', models.CharField(help_text='SHA-256 hash for duplicate detection', max_length=64)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='processing', max_length=30)),
                ('row_count', models.IntegerField(default=0, help_text='Total rows parsed from file')),
                ('success_count', models.IntegerField(default=0, help_text='Rows successfully normalized')),
                ('error_count', models.IntegerField(default=0, help_text='Rows that failed parsing/validation')),
                ('processing_log', models.JSONField(blank=True, default=list, help_text='Detailed log of parsing and validation messages')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestions', to='core.tenant')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Data ingestions',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RawRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_number', models.IntegerField(help_text='Line number in the source file (1-indexed)')),
                ('raw_data', models.JSONField(help_text='Complete original row as key-value pairs')),
                ('parse_status', models.CharField(choices=[('parsed', 'Successfully Parsed'), ('failed', 'Parse Failed'), ('skipped', 'Skipped')], default='parsed', max_length=20)),
                ('parse_errors', models.JSONField(blank=True, default=list, help_text='Array of error messages from parsing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.dataingestion')),
                ('tenant', models.ForeignKey(help_text='Denormalized from ingestion for query performance', on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='core.tenant')),
            ],
            options={
                'ordering': ['ingestion', 'row_number'],
                'indexes': [models.Index(fields=['tenant', 'ingestion'], name='ingestion_r_tenant__d73370_idx'), models.Index(fields=['parse_status'], name='ingestion_r_parse_s_f5a0dd_idx')],
            },
        ),
    ]
