# Generated by Django 4.2.30 on 2026-05-24 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportLookup',
            fields=[
                ('iata_code', models.CharField(help_text='IATA 3-letter code', max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Airport name', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2', max_length=2)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
            ],
            options={
                'ordering': ['iata_code'],
            },
        ),
        migrations.CreateModel(
            name='PlantCodeLookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(help_text='SAP Werk code, e.g. 1000', max_length=10)),
                ('facility_name', models.CharField(help_text='Human-readable facility name', max_length=255)),
                ('country', models.CharField(help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('region', models.CharField(blank=True, help_text='Region for grid emission factor lookup', max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_codes', to='core.tenant')),
            ],
            options={
                'ordering': ['tenant', 'plant_code'],
                'unique_together': {('tenant', 'plant_code')},
            },
        ),
    ]
