# Generated by Django 4.2.30 on 2026-05-24 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_db', models.CharField(help_text='Factor database, e.g. DEFRA_2024, EPA_2024, custom', max_length=50)),
                ('category', models.CharField(choices=[('fuel', 'Fuel Combustion'), ('electricity', 'Grid Electricity'), ('travel_air', 'Air Travel'), ('travel_hotel', 'Hotel Stay'), ('travel_car', 'Car / Ground Transport')], max_length=30)),
                ('activity_type', models.CharField(help_text='e.g. diesel, petrol, natural_gas, grid_electricity, short_haul_economy', max_length=100)),
                ('sub_type', models.CharField(blank=True, help_text='Further classification, e.g. with_rf, without_rf', max_length=100, null=True)),
                ('unit', models.CharField(help_text='Factor is per this unit: L, kWh, pkm, night, km', max_length=30)),
                ('co2e_per_unit', models.DecimalField(decimal_places=8, help_text='kg CO₂e per unit (total GHG impact)', max_digits=12)),
                ('co2_per_unit', models.DecimalField(blank=True, decimal_places=8, help_text='kg CO₂ per unit (CO₂ only)', max_digits=12, null=True)),
                ('ch4_per_unit', models.DecimalField(blank=True, decimal_places=8, help_text='kg CH₄ per unit', max_digits=12, null=True)),
                ('n2o_per_unit', models.DecimalField(blank=True, decimal_places=8, help_text='kg N₂O per unit', max_digits=12, null=True)),
                ('valid_from', models.DateField(help_text='Factor valid from this date')),
                ('valid_to', models.DateField(blank=True, help_text='Factor valid until (null = current)', null=True)),
                ('region', models.CharField(blank=True, help_text='Applicable region/country, e.g. UK, US, IN, DE', max_length=50, null=True)),
            ],
            options={
                'ordering': ['category', 'activity_type'],
            },
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1 - Direct Emissions'), ('scope_2', 'Scope 2 - Indirect Energy'), ('scope_3', 'Scope 3 - Value Chain')], max_length=10)),
                ('scope_category', models.CharField(help_text='e.g. stationary_combustion, purchased_electricity, business_travel_cat6', max_length=100)),
                ('activity_type', models.CharField(help_text='e.g. diesel_combustion, grid_electricity, flight_short_haul_economy', max_length=100)),
                ('quantity', models.DecimalField(decimal_places=6, help_text='Quantity in normalized unit', max_digits=16)),
                ('unit', models.CharField(help_text='Normalized unit: L, kWh, pkm, night, km', max_length=20)),
                ('original_quantity', models.DecimalField(decimal_places=6, help_text='Quantity as received from source', max_digits=16)),
                ('original_unit', models.CharField(help_text='Unit as received from source', max_length=30)),
                ('period_start', models.DateField(help_text='Activity period start')),
                ('period_end', models.DateField(blank=True, help_text='Activity period end (null for point-in-time events)', null=True)),
                ('facility_code', models.CharField(blank=True, help_text='Plant code, meter ID, or similar identifier', max_length=50)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('co2e_kg', models.DecimalField(decimal_places=4, help_text='Calculated kg CO₂e = quantity × emission_factor', max_digits=14)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('flagged', 'Flagged for Review')], default='pending', max_length=20)),
                ('flags', models.JSONField(blank=True, default=list, help_text="Auto-detected anomaly flags, e.g. [{type: 'high_value', severity: 'warning', message: '...'}]")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Analyst comments on this record')),
                ('is_locked', models.BooleanField(default=False, help_text='True after audit approval — record becomes immutable')),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField(default=1, help_text='Incremented on each edit for optimistic concurrency')),
                ('emission_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emission_records', to='emissions.emissionfactor')),
                ('ingestion', models.ForeignKey(help_text='Which upload produced this record', on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.dataingestion')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_records', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(help_text='Link to the original raw source row', on_delete=django.db.models.deletion.CASCADE, related_name='emission_record', to='ingestion.rawrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_records', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='core.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['category', 'activity_type'], name='emissions_e_categor_e02c03_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionfactor',
            index=models.Index(fields=['region'], name='emissions_e_region_491d48_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'scope'], name='emissions_e_tenant__80b9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'review_status'], name='emissions_e_tenant__1dfd87_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['tenant', 'ingestion'], name='emissions_e_tenant__fb7b50_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['scope', 'activity_type'], name='emissions_e_scope_9aee96_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['review_status'], name='emissions_e_review__5517f6_idx'),
        ),
        migrations.AddIndex(
            model_name='emissionrecord',
            index=models.Index(fields=['is_locked'], name='emissions_e_is_lock_c0ba56_idx'),
        ),
    ]
