# Generated by Django 4.2.30 on 2026-05-24 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('created', 'Record Created'), ('updated', 'Record Updated'), ('approved', 'Record Approved'), ('rejected', 'Record Rejected'), ('flagged', 'Record Flagged'), ('locked', 'Record Locked for Audit'), ('unlocked', 'Record Unlocked')], max_length=20)),
                ('field_changed', models.CharField(blank=True, help_text='Which field was modified (empty for create/approve/reject)', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value')),
                ('new_value', models.TextField(blank=True, help_text='New value')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional context, e.g. ingestion_id, batch info')),
                ('emission_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.emissionrecord')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant')),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['tenant', 'emission_record'], name='review_audi_tenant__8f03e9_idx'), models.Index(fields=['action'], name='review_audi_action_aaa40c_idx'), models.Index(fields=['performed_at'], name='review_audi_perform_02731b_idx')],
            },
        ),
    ]
